Repository Martyna-Tu/object-oriented-programming, pull requests merged in 2021-07, with the labels that each got.

#29 Added ptr check to getSpeed() method in Player class
  shm/Player.cpp
Labels: bug

#34 Player class overhauled
  shm/Player.cpp
  shm/Player.hpp
Labels: bug, documentation

#36 Store work.
  .gitignore
  shm/CMakeLists.txt
  shm/Cargo.cpp
  shm/Cargo.hpp
  shm/Island.cpp
  shm/Island.hpp
  shm/Map.cpp
  shm/Player.cpp
  shm/Player.hpp
  shm/Ship.cpp
  shm/Ship.hpp
  shm/Store.cpp
  shm/Store.hpp
  shm/Tests.cpp
  shm/main.cpp
Labels: enhancement

#44 Convert Cargo into interface.
  shm/Alcohol.cpp
  shm/Alcohol.hpp
  shm/CMakeLists.txt
  shm/Cargo.cpp
  shm/Cargo.hpp
  shm/Fruit.cpp
  shm/Fruit.hpp
  shm/Item.cpp
  shm/Item.hpp
  shm/Tests.cpp
  shm/main.cpp
Labels: enhancement

#45 Refactor split, getName, generateCargo and tests.
  shm/Alcohol.cpp
  shm/Alcohol.hpp
  shm/CMakeLists.txt
  shm/Cargo.cpp
  shm/Cargo.hpp
  shm/DefaultCargo.cpp
  shm/DefaultCargo.hpp
  shm/Fruit.cpp
  shm/Fruit.hpp
  shm/Island.hpp
  shm/Item.cpp
  shm/Item.hpp
  shm/Map.cpp
  shm/Map.hpp
  shm/Ship.cpp
  shm/Ship.hpp
  shm/Store.hpp
  shm/Tests.cpp
  shm/main.cpp
Labels: enhancement

#67 Add CI. Add flags and changes to CMakeLists.txt. Fix bugs and warnings.
  .github/workflows/main.yml
  shm/Alcohol.cpp
  shm/CMakeLists.txt
  shm/DryFruit.cpp
  shm/Fruit.cpp
  shm/Island.hpp
  shm/Item.cpp
  shm/Perishable.hpp
  shm/Ship.cpp
  shm/Ship.hpp
  shm/Store.cpp
  shm/Store.hpp
  shm/Tests.cpp
  shm/Time.cpp
  shm/Time.hpp
  shm/main.cpp
Labels: enhancement
